- README.md
- examples/serverside-options/index.js
- src/MUIDataTable.js
- src/MUIDataTableBody.js
This PR will provide the ability to load in filter list data and a starting page for pagination.
When merged it will close #16 #38
> server side options for pagination and filter list

- README.md
- examples/text-localization/index.js
- src/MUIDataTable.js
- src/MUIDataTableBody.js
- src/MUIDataTableFilter.js
- src/MUIDataTableHeadCell.js
- src/MUIDataTablePagination.js
- src/MUIDataTableSearch.js
- src/MUIDataTableToolbar.js
- src/MUIDataTableToolbarSelect.js
- src/MUIDataTableViewCol.js
- src/textLabels.js
- test/MUIDataTable.test.js
- test/MUIDataTableBody.test.js
- test/MUIDataTableFilter.test.js
- test/MUIDataTableHeadCell.test.js
- test/MUIDataTablePagination.test.js
- test/MUIDataTableSearch.test.js
- test/MUIDataTableToolbar.test.js
- test/MUIDataTableToolbarSelect.test.js
- test/MUIDataTableViewCol.test.js
This PR should bring in support to override the text strings throughout the library that are in english.
When merged will close #35 
Todo: Finish README explaining how to use this new feature
> new feature: text localization support

- README.md
- examples/customize-toolbarselect/CustomToolbarSelect.js
- examples/customize-toolbarselect/index.js
- examples/serverside-options/index.js
- src/MUIDataTable.js
- src/MUIDataTableBody.js
- src/MUIDataTableToolbarSelect.js
- test/MUIDataTable.test.js
- test/MUIDataTableBody.test.js
- test/MUIDataTableToolbarSelect.test.js
- webpack.config.js
When merged this should close #47 #27 
**TODO:** 
- Add prop for selectedRows to support controlled components
- Fix unit tests
> new feature: render custom selected rows toolbar + dataIndex on selectedRows callback

- README.md
Just noticed it was on the code but not on `README.md`, thought I could give my 2 cents on that.
> Add missing viewColumns option on README.md

- .eslintrc
- examples/component/cities.js
- examples/component/index.js
- package-lock.json
- package.json
- src/MUIDataTable.js
- test/MUIDataTable.test.js
- webpack.config.js
When merged this should address #63 
@jkantr and @samsch would love some feedback on this PR.
> add tableMeta to customRender function

- package-lock.json
- src/MUIDataTableToolbar.js
For me, it fix the #86 issue i created. I hope it will not create bug for other people.
> fix csv-export bug

- README.md
- examples/component/index.js
- examples/selectable-rows/index.js
- src/MUIDataTable.js
- src/MUIDataTableBody.js
- src/MUIDataTableBodyCell.js
- src/MUIDataTableFilter.js
- test/MUIDataTableBody.test.js
- webpack.config.js
This should solve #75 and also #73 when merged 
@rst66 @adetwiler @jstgermain
> add count support for options + onCellClick callback

- docs/pages/index.js
- package-lock.json
- package.json
- src/MUIDataTableToolbar.js
- test/MUIDataTableToolbar.test.js
> Upgrade Material-UI Icons to v2.0.0

- src/MUIDataTableHeadCell.js
> Enable sorting by column only when sort is enabled for column

- README.md
- examples/simple/index.js
- package-lock.json
- package.json
- src/MUIDataTable.js
- src/MUIDataTableHead.js
- src/MUIDataTableResize.js
- test/MUIDataTableHead.test.js
- webpack.config.js
When merged, this should close #112
> new feature: resizeable columns

- README.md
- src/MUIDataTableToolbar.js
Right now, no params are returned. Don't know if it's relevant to return some.
> #145 Add callback function when search input is closed

- src/MUIDataTableResize.js
Should resolve #164 when merged
> fix column resize bug

- src/MUIDataTable.js
Add Reload for rowsSelected option
Fix reload if page is set to 0
According to #154
> Fix reloading options + add rowsSelected as reloaded

- README.md
- examples/customize-columns/index.js
- src/MUIDataTable.js
- src/MUIDataTableBody.js
- src/MUIDataTableHead.js
- src/MUIDataTableViewCol.js
- test/MUIDataTable.test.js
- test/MUIDataTableHead.test.js
- webpack.config.js
When merged, this should resolve #68
> change column display to enum: ('true', 'false', 'excluded')

- package.json
- src/MUIDataTableBody.js
- src/MUIDataTableToolbar.js
- src/MUIDataTableToolbarSelect.js
This includes all changes to Typography classes
> Upgrade material-ui/core version to 3.2.0

- src/MUIDataTableToolbar.js
> IE export csv bug fixed

- package-lock.json
- package.json
- src/MUIDataTable.js
When merged this should resolve #218
> fix for serverSide sorting issue #218

- src/MUIDataTable.js
- src/MUIDataTableBody.js
- src/MUIDataTableToolbar.js
- src/MUIDataTableViewCol.js
When merged should resolve #192 #207
> fix select all issue #192 #207

- .gitignore
- src/MUIDataTable.js
- test/MUIDataTable.test.js
Fix `MUIDataTable` changeRowsPerPage method
After merge it will fix #242
> Fix for changing rows per page issue

- .gitignore
- src/MUIDataTableBody.js
- src/MUIDataTableToolbar.js
- src/MUIDataTableToolbarSelect.js
https://material-ui.com/style/typography/#migration-to-typography-v2
Fixes #251
> Migration to typography v2

- docs/pages/index.js
- package-lock.json
- src/MUIDataTableBody.js
- src/MUIDataTableToolbar.js
- src/MUIDataTableToolbarSelect.js
Upgraded Typography variants to use the new variants implemented in Material UI v3.2.1 onwards
Closes #245
> Upgrade Typography to use v2 variants

- src/MUIDataTableToolbar.js
Using data instead of displayData? there's a specific functionality missing if we use data? we can prevent the React elements?
> I've tested based on issue #275 the download CSV

- src/MUIDataTable.js
> Fix issue with sort not taking into account on re-render

- README.md
- src/MUIDataTable.js
when merged this should close #258 #137
> enhancement: allow elevation change on Paper component

- src/MUIDataTable.js
> bugfix: make dropdown default filter

- src/MUIDataTable.js
- src/components/TableResize.js
> bugfix: fix resizeable column coords when serverside true

- package-lock.json
- src/components/TableBody.js
This should close #333. Somehow, not all changes in PR #277 survived the reorganization...
> Update variant prop in TableBody to new Material V2 names

- src/MUIDataTable.js
> bugfix: page size out of bounds when searching

- src/components/TableBody.js
When serverSide is true empty data list doesn't display proper messages. #253
> Fix bug #253

- src/utils.js
> #385 CSV export, escape " in column header name

- src/MUIDataTable.js
#408 
Don't query for hidden column values
> Exclude hidden columns from search results

- README.md
Hi !
I think there is a small mistake in the documentation :)
> fix setCellProps return type in README

- src/components/TableFilter.js
Hi there, I think this was causing a bug for me when I was using the filter table functionality.
> Allow for checking null and undefined.

- README.md
- examples/data-as-objects/index.js
- package-lock.json
- src/MUIDataTable.js
- webpack.config.js
this should resolve the following issues: #331 #7 #147
> add support for data as objects

- src/components/TableFilter.js
another potential fix for #299
> undefined is not being caught in filters

- src/MUIDataTable.js
Fixes issue https://github.com/gregnb/mui-datatables/issues/461
> Fixes issue #461 expandable rows after sorting

- src/components/TableFilter.js
> Fixes #464: Handle 'All' filter when filter text label 'All' is translated

- src/MUIDataTable.js
- test/MUIDataTable.test.js
> Fix #414 - Disable client side filtering when server side filtering is enabled.

- docs/pages/index.js
Currently you are referencing v1 in your doc for material ui, however it is using the current version. Updating the document's reference.
> Reference MUI v3 instead of v1

- src/MUIDataTable.js
- src/components/TableToolbar.js
- test/MUIDataTableToolbar.test.js
For example
```jsx
<MUIDataTable title={<small>Title</small>}/>
```
> Support for React Component on title prop

- examples/array-value-columns/index.js
- examples/hide-columns-print/index.js
- src/MUIDataTable.js
- test/MUIDataTable.test.js
Allows the ability to filter based on array values in a single cell.  Addresses Issue #546.
Please let me know if there is anything additional I should do or change.  This is my first time creating a PR and contributing to open source! :smile:  
Example pictures below.
> added the ability to filter columns with array values

- README.md
- examples/column-filters/index.js
- src/MUIDataTable.js
- src/components/TableFilterList.js
- test/MUIDataTable.test.js
Added customFilterListRender to column options (identity function as default)
> Rendering of filters (#407) 

- examples/serverside-pagination/index.js
Closes https://github.com/gregnb/mui-datatables/issues/146 with example for demonstration purposes.
> Add loading examples to serverside example

- README.md
Added on README file the info for start to collaborate.
> Added collaboration info

- src/components/TableHeadCell.js
- src/components/TableHeadRow.js
Possible solution to issue #611
> header wrap fix

- src/components/TableFilter.js
Bug fix for renderMultiselect filter breaking for null values
> renderMultiselect filter type for null values

- examples/serverside-pagination/index.js
- package-lock.json
- src/MUIDataTable.js
- webpack.config.js
Fix the `count` does not refresh from server
> Fix issue #610 about count from server does not refresh

- src/components/TableFilter.js
Increase robustness of fix for https://github.com/gregnb/mui-datatables/issues/299.
> Handle undefined values for multiselect filters

- src/MUIDataTable.js
- src/components/TableFilter.js
In previous version, it looks like options were being updated everytime in componentWillRecieveProps. But it was removed and options were not being applied if they were updated.
I can elaborate the use case if you want.
> Updates 'options' in componentDidUpdate

- src/MUIDataTable.js
Closes #673 by moving the argument to the correct place
> Move the column argument to the correct position

- src/MUIDataTable.js
> Undo any deep overwriting of array

- examples/on-table-init/index.js
Use a more familiar approach to handling react data so that people using the example may have an easier time
> Use state and pull data out of render

- src/MUIDataTable.js
Fixes https://github.com/gregnb/mui-datatables/issues/767.
> Fix issue with selecting the proper row after sorting

- src/MUIDataTable.js
Fixes https://github.com/gregnb/mui-datatables/issues/312.
> Fix issues with overflow for responsive stacked view

- src/components/TableSelectCell.js
fix for #792
quick view: https://codesandbox.io/s/github/patorjk/mui-datatables
> Set selectable row checkbox color through attribute

- test/MUIDataTable.test.js
passing test for #711 (originally from my issue #657)
> add test for #711

- package-lock.json
- package.json
- src/MUIDataTable.js
- We needed to update options before we call table updates
- We also needed to ensure that we overwrite our new options (merge does not overwrite)
> Fix isRowSelectable update issues

- README.md
> Fix available 'rowsPerPageOptions' in documentation

- src/components/TableHeadCell.js
#858 - Trigger sorting via keyboard doesnt't seem to work
> Fix for #858

- README.md
- src/MUIDataTable.js
- src/components/TableBody.js
Minor improvements to documentation, prop types, and callback.
> Improve documentation and plumbing for rows selection

- src/MUIDataTable.js
Resolves https://github.com/gregnb/mui-datatables/issues/580#issuecomment-529796114
> Fix issue with scroll full height using incorrect class name

- test/MUIDataTable.test.js
Supplement to https://github.com/gregnb/mui-datatables/pull/877.
> Add failing test for sorting columns with undefined data

- examples/custom-action-columns/index.js
- src/MUIDataTable.js
Closes https://github.com/gregnb/mui-datatables/issues/901
> Issue 901 - Fix inconsistent table meta

- src/MUIDataTable.js
Closes https://github.com/gregnb/mui-datatables/issues/966.
> Allow sort direction of "none" to be applied multiple times

- src/MUIDataTable.js
Closes https://github.com/gregnb/mui-datatables/issues/1007.
> Prevent overflows from preventing sticky headers

- src/components/TableToolbar.js
Closes https://github.com/gregnb/mui-datatables/issues/1033.
> Fix download row order when using display true options

- README.md
- package-lock.json
- src/MUIDataTable.js
- test/MUIDataTable.test.js
With the release of `material-ui@4.0.0` the [table component](https://material-ui.com/api/table/#props) has new properties. Currently there is no way to pass any properties to the material-ui table component, as is supported for rows and cells.
This PR introduces a new table options property `tableProps`. `tableProps` is an object and is applied directly to the material-ui table component
> Add table properties option

- src/MUIDataTable.js
- src/components/TableBody.js
- src/utils.js
- test/MUIDataTable.test.js
Currently there are some deprecation warnings that show up in production code, not sure what your opinion is @gabrielliwerant, but I think its enough to know about the deprecations when developing locally, no need for error reporters to see it I think.
> Deprecation warnings

- examples/customize-filter/index.js
https://github.com/gregnb/mui-datatables/issues/1216
Hello?
I really like this library.
But the example is wrong
So I tried to fix it. 😃
> Fix customize-filter example

- README.md
...near the beginning of page. 
It provides an easier navigation, otherwise it's tiresome to scroll back and forth.
> Updated README to add a table of content

- src/components/Popover.js
- src/components/TableFilter.js
- src/components/TableToolbar.js
> Close icon to Popover & typo fix

- src/components/TableResize.js
this is fix for issue #1164 
Still not perfect one, as resizers tend to move into one direction after several resizings, but works  quite OK.
> fix for #1164

- examples/customize-styling/index.js
- src/components/TableBody.js
This PR resolves issue #1241 
This PR adds rowIndex as third argument for setRowProps.
Tell me if it's good for you @patorjk :)
> Add rowIndex as third argument for setRowProps

- src/MUIDataTable.js
> Refactor column direction conversion

- src/MUIDataTable.js
Reverts gregnb/mui-datatables#995
> Revert "Refactor column direction conversion"

- package-lock.json
- src/components/TableHead.js
> Checkbox in TableHead shows checked if data is empty which is confusing on load

- src/components/Popover.js
- src/components/TableToolbar.js
- src/components/TableViewCol.js
ref : #1323
viewColumn closeIcon not working
Fix
> Fix popover bug 

- src/MUIDataTable.js
With all entire row object in logic fn filtering can be more powerful 
Related with: https://github.com/gregnb/mui-datatables/issues/1307
> Add row param for column.filterOptions.logic

- src/components/TableHead.js
- src/components/TableHeadCell.js
- src/components/TableHeadRow.js
Refactor from class component to functional component
ref : #1346
Sorry. When I split it in PR, it's lot..
codeSandBox : http://codesandbox.io/s/github/wdh2100/mui-datatables/tree/functional/tableHead
> Refactoring TableHead

- src/components/TableFilterList.js
- src/components/TableFilterListItem.js
Change from Class Component to Functional component
Hello~ 😃
React seems to be changing to a functional component(= pure component). (my opinion)
We need to be a functional component to use a lot of cool Hooks.
I'll go ahead with the test to see if I have any performance gains.
But in my opinion ❓ , I feel more comfortable with the functional component than the class component.
I'm going to need a lot of tests because I'm going to change the whole component
thanks!
happy coding~
ref : #1338 
codeSandBox : http://codesandbox.io/s/github/wdh2100/mui-datatables/tree/functional/tableFIlter
> Refactoring TableFilterList and TableFilterListItem

- src/components/TableFilterList.js
- src/components/TableFilterListItem.js
Reverts gregnb/mui-datatables#1346
> Revert "Refactoring TableFilterList and TableFilterListItem"

- src/components/TableHead.js
- src/components/TableHeadCell.js
- src/components/TableHeadRow.js
Reverts gregnb/mui-datatables#1352
> Revert "Refactoring TableHead"

- src/components/TableHead.js
- src/components/TableHeadCell.js
- src/components/TableHeadRow.js
Reverts gregnb/mui-datatables#1355
> Revert "Revert "Refactoring TableHead""

- src/components/TableFilterList.js
- src/components/TableFilterListItem.js
Reverts gregnb/mui-datatables#1354
> Revert "Revert "Refactoring TableFilterList and TableFilterListItem""

- src/components/TablePagination.js
Refactor from class component to functional component
ref : #1346
Sorry. When I split it in PR, it's lot..
odeSandBox : http://codesandbox.io/s/github/wdh2100/mui-datatables/tree/functional/tablePagination
> Refactoring TablePagination

- package-lock.json
- package.json
- src/MUIDataTable.js
* Fix for server side compiling: https://github.com/gregnb/mui-datatables/issues/1368
> version 3.1.3

- examples/customize-filter/index.js
- examples/simple/index.js
- package-lock.json
- package.json
- src/MUIDataTable.js
- src/components/TableBody.js
- src/components/TableFilter.js
- src/components/TableHead.js
- test/MUIDataTableBody.test.js
Fixes for:
* https://github.com/gregnb/mui-datatables/issues/1383
* https://github.com/gregnb/mui-datatables/issues/1380
> Reset filter and setRowProps bug fix

- examples/customize-footer/index.js
- examples/customize-styling/index.js
related #1409 
The example is also modified.
thanks!
Because it was deleted.
> Replace classnames with clsx in example

- src/MUIDataTable.js
- src/components/TableFilter.js
- src/components/TableResize.js
- src/hooks/useColumnDrop.js
- src/utils.js
- test/MUIDataTable.test.js
- test/MUIDataTableFilter.test.js
- test/MUIDataTableToolbar.test.js
- test/MUIDataTableToolbarSelect.test.js
- test/TableResize.test.js
- test/UseColumnDrop.test.js
- test/setup-mocha-env.js
- test/utils.test.js
Just some updates to get the test coverage above 80%.
> Test Coverage Updates

- examples/simple/index.js
- src/MUIDataTable.js
Resets sorting on the third click
> Reset sorting

- examples/resizable-columns/index.js
- src/components/TableResize.js
- test/MUIDataTable.test.js
Fix for https://github.com/gregnb/mui-datatables/issues/1433
> Fix for resizable tables when selectableRows="none"

- src/components/TableToolbar.js
Added displayedData prop to CustomToolbar in TableToolbar.
> added displayedData prop to customtoolbar

- package.json
3.7.0 Release
- Replace gridList to grid at filter (#1559)
- BugFix onFilterDialogClose event (#1563)
- Implement bundle with babel core-js@3 (IE support)
> Version 3.7.0

- .babelrc
- package-lock.json
- package.json
- rollup.config.js
> Version 3.7.1

- src/MUIDataTable.js
- Add types boolean (true,false)
https://github.com/gregnb/mui-datatables/issues/1576
Name | Type | Default
-- | -- | --
display | `boolean or string`
> Fix columns option display PropTypes

- src/components/ExpandButton.js
- src/components/TableHead.js
- src/components/TableSelectCell.js
Fix #1591
- Refactoring TableSelectCell
- Refactoring ExpandButton
> Fix selectableRowsHideCheckboxes(#1591) bug

- src/components/TableHeadCell.js
This fixes [#1606](https://github.com/gregnb/mui-datatables/issues/1606)
https://user-images.githubusercontent.com/26791103/103573617-4e021480-4ead-11eb-83bd-c29a2132b5ab.mov
> fix: header tooltips bug #1606

- README.md
- package.json
> Release 3.7.5

- src/components/TableHeadCell.js
bugfix https://github.com/gregnb/mui-datatables/issues/1652
> bugfix wrong props

- package.json
> release 3.7.6

- README.md
> Typo Fix in  doc

- package.json
Fix peerDependencies react v17
- https://github.com/gregnb/mui-datatables/issues/1658
- https://github.com/gregnb/mui-datatables/issues/1660
> Fix peerDependencies react v17

- src/MUIDataTable.js
Fix impoting level
ref : https://github.com/gregnb/mui-datatables/issues/1676
https://github.com/gregnb/mui-datatables/issues/1676
> Fix material-ui/core second level import

- src/components/TableBody.js
- src/components/TableBodyCell.js
- src/components/TableHeadCell.js
> fix two issues

- README.md
- src/localStorage/load.js
- for nextJS
https://github.com/gregnb/mui-datatables/issues/1806
> fix : Changed to work only in browser(storageKey)

- src/components/TableBodyCell.js
These were added in 940fee7b740dba578fc65e08a1321589a730c88a and are spamming the client. May resolve #1873 but I haven't been able to test it against the project yet.
> v3 - Remove console.logs

- examples/Router/index.js
- package-lock.json
- package.json
- src/plug-ins/DebounceSearchRender.js
This PR upgrades React to `18` and `mui/*` packages to the latest stable release.
> refactor: upgrade `React` to `18` and `mui/*` to `latest`
