gregnb/mui-datatables

src/MUIDataTableToolbar.js

Calling CSV Download button on Unicode data will cause a InvalidCharacterError exception because window.btoa supports characters inside the range 0x00 to 0xFF. 
This PR fixed the problem by encoding extended characters to their ASCII representation

Fix csv export for unicode data

---

src/MUIDataTableBody.js

When selectableRows is set to false, the noMatch text is set to the number of columns.

Corrected noMatch column width, fixes #77

---

README.md

Fixes #163 
Clarifies the meaning of the second parameter to `onRowsSelect` to imply that it is all of the rows selected.

Clarification on onRowSelect option

---

README.md
examples/serverside-pagination/index.js
src/MUIDataTable.js
test/MUIDataTable.test.js

I'd like to be able to subscribe to the table state as a whole for any action regardless of the serverSide option, in order to treat the table as more of a controlled component.
Usecase: I want to allow a user to change the shape of the table and save the structure. I am using the table as form component of sorts.
I've started with piggybacking on the setServerRequest (renamed to setTableAction), and continued with selectRowUpdate, selectRowDelete and columnViewChange.
If this is helpful and desired, great. If you think there is a better route let me know :)
Cheers,
JP

Add a onTableChange callback to get table state upon any action

---

src/textLabels.js

selectedRows text label typo fix

---

src/MUIDataTable.js

Currently, during the search when the server side data is passed on to the datatable, it again filters the data using local search logic. In the computeDisplayRow() function, it doesn't check if the options.serverSide is false or not.

Perform search only if serverSide is falsy

---

README.md
examples/customize-toolbarselect/CustomToolbarSelect.js
examples/customize-toolbarselect/index.js
src/MUIDataTable.js
src/MUIDataTableToolbarSelect.js
test/MUIDataTable.test.js
test/MUIDataTableToolbarSelect.test.js

Added two additional parameters to `customToolbarSelect`: 
- `displayData` - an array of actual displaying data in the table. It's may be used for calculating next selected rows
- `setSelectedRows` - a function, that receives `selectedRows` (array of numbers - indexes of selected rows). It's may be used to set imperatively selected rows after user click on action button from your customToolbarSelect.
Also, I've updated documentation and example `customize-toolbarselect` (need to deploy to firebase).
This PR will cover #266

[Feature] Custom toolbar select with imperative setSelectedRows

---

src/MUIDataTableBodyCell.js
src/MUIDataTableBodyRow.js
src/MUIDataTableHead.js
src/MUIDataTableSelectCell.js
src/MUIDataTableToolbar.js

Using the MUI theme breakpoints prevents off-by-one incongruencies with
applications rendering datatables using the default breakpoints. It also
enables application developers to customize the MUI breakpoints without
jarring experience when using `mui-datatables`. Closes #269.
NOTE: There were a couple places with very small media queries which don't have a MUI equivalent. I left those media queries intact: [MUIDataTablePagination](https://github.com/gregnb/mui-datatables/blob/0297bb6b21effdf1a6d4264e22b8b1307020140b/src/MUIDataTablePagination.js#L16) and [MUIDataTableToolbar](https://github.com/gregnb/mui-datatables/blob/0297bb6b21effdf1a6d4264e22b8b1307020140b/src/MUIDataTableToolbar.js#L77) (specifies no styles?)
I manually verified that each of the updated media queries worked as …

Use MUI theme breakpoint media queries

---

README.md
src/MUIDataTable.js
src/MUIDataTableToolbar.js

This PR adds a new `onSearchOpen` callback triggered when the search box is displayed and also closes https://github.com/gregnb/mui-datatables/issues/210
Example of how to use this callback:
```
const options = {
filter: true,
filterType: 'dropdown',
responsive: 'stacked',
onSearchOpen: ()=>{
// your code here will be run after the user opens the search box
},
};
return (
<MUIDataTable title={"ACME Employee list"} data={data} columns={columns} options={options} />
);
```

New onSearchOpen Callback

---

src/MUIDataTable.js
src/MUIDataTableToolbar.js
src/MUIPopover/MUIDataTablePopoverWrapper.js
src/MUIPopover/MUIPopover.js

Fixes #252
This fixes an issue with re-rendering the complete Toolbar on data changes (filtering or column view changes) which resulted in the Filter Popover being closed and reopened when clicking on a filter or checking or unchecking a column in column view for the first time.
The issue was caused by the `tableRef` which was passed from the MuiDataTable instance down to the popover to be used as container.
This ref updated when the table was re-rendered and caused all components using it to also re-render.
As the prop was passed as a function which returned the ref, React considered the property changed on each re-render as the function would not be the same
see https://reactjs.org/docs/faq-functions.html
I also refactored  the popovers to be PureComponents and cleaned up the …

#252: fix filter re-render bug 

---

src/MUIDataTable.js
test/MUIDataTable.test.js

First of all, thank you for creating this great package!
I recently discovered that in some browsers (like Android Web View or older versions of mobile Safari), there is no support for the `Intl` API. In order to prevent crashes on these devices, I propose to feature detect for `Intl` and fall back to a plain string comparison in cases where `Intl` is not available.

Feature detect "Intl" and use plain string comparison when not available

---

README.md
examples/selectable-rows/index.js
src/MUIDataTableHead.js
src/MUIDataTableHeadCell.js
test/MUIDataTableHeadCell.test.js

This adds the option to add a custom hint tooltip to column headers by setting the `hint` property on column options.

Custom column hint tooltip

---

README.md

I spotted a little mistake on the README on the line about `onFilterChange`, the commit just fixes the breakline before `avoid` word.

Fix `onFilterChange` line in README

---

README.md
examples/customize-styling/index.js
src/MUIDataTableBody.js
src/MUIDataTableBodyCell.js
src/MUIDataTableBodyRow.js
test/MUIDataTableBody.test.js
webpack.config.js

fixes #304 
This adds 2 functions
On table options:
`getRowClassName`
which is called for each row and adds classes returned from it to the `MUIDataTableBodyRow`  object .
Allows styling of each row based on its data
And `getRowClassName` on column options, which does the same for cells

add custom styling methods for rows and cells

---

src/MUIDataTable.js

When using the `customSort` prop, if the sort function provided doesn't sort `data` in place but returns a copy of `data` sorted, the original (unsorted) `data` is used to pick indexes... which results in no sorting happening in the table.
This PR ensures that the sorted list is used when reading indexes.

Fix sorting when customSort doesn't sort inplace

---

src/components/TableBody.js

The noMatch in TableBody options can be useful to customize the loading/table-display when there are no results:
```
textLabels: {
body: {
noMatch: data.length === 0 ?
<i className='fas fa-circle-notch fa-spin fa-lg'/> :
'Sorry, there is no matching data to display'
},
}
```
If, in the options, serverSide is set to true, this label gets ignored because it's not possible to pass null as data to the TableBody. So, **I couldn't find any means of customizing the label when in serverSide mode.**
This request intends to restore that ability and replicate the behaviour (as it happens without serverSide).

Allow the customization of noMatch in textLabels

---

README.md
examples/selectable-rows/index.js
src/MUIDataTable.js
src/components/TableBody.js
src/components/TableHead.js
src/components/TableSelectCell.js

As mentioned in https://github.com/gregnb/mui-datatables/issues/172 by @brianpmaher 
with added following option in examples/selectable-rows/index.js
```
isSelectable: (dataIndex) => {
//prevents selection of row with title "Attorney"
return data[dataIndex][1] != "Attorney";
}
```
With select all clicked

feature: Option to disable selection on certain rows

---

README.md
src/MUIDataTable.js
src/components/TableFilter.js
test/MUIDataTable.test.js
test/MUIDataTableFilter.test.js

Adds a `textField` type to the `filterType` options. 
This PR allows users to select `textFeild` for the filter type, which will allows users to start typing to filter a particular column.
Here is what it looks like when the filter is active:
Here is what it looks like when the filter tab is open:

Adding "textField" filter type (#342)

---

examples/themes/index.js
src/MUIDataTable.js
src/components/TableBodyCell.js
src/components/TableFilter.js
src/components/TableHeadCell.js
src/components/TableSearch.js
src/components/TableSelectCell.js
src/components/TableToolbar.js
src/components/TableToolbarSelect.js
src/components/TableViewCol.js

This is essentially a copy of #300 but updated to work with the
new layout. It also replaces all colors I could find to be sure
they refrence the themes and still look good on both light and
dark themes.
See #300 for what the screenshots look like as they are
an example. Also, I added a new theme example that will render
dark by default.

Updating colors to work with the MUI themes.

---

src/components/TableBody.js

Use the number of non-excluded columns instead of the total number of columns.

Fix TableBodyCell colSpan for empty table

---

src/MUIDataTable.js

Applications, rather than mui-datatables, ought to be the ones
responsible for setting whether or not to use the new typography
variants. The flag does not need to be enabled in order to _use_ the new
variants. The flag mainly controls whether or not MUI will warn about
the usage of deprecated variants so applications can ensure they have
completely migrated away completely.
Resolves #398

Do not force MUI to require new typography variants

---

rollup.config.js
src/index.js

This addresses #291.
Note that because this library is exported as a CommonJS module, this can break compatibility. Thoughts on introducing this?

Export subcomponents

---

src/components/TableBody.js

At the moment, if you have an `onRowClick`-handler on a selectable row, the handler will be called when the user clicks the checkbox. I'm unsure if this is on purpose or not, but I have a hard time coming up with a scenario, where you want the click handler to be called on selection as well.
This PR fixes that, so the `onRowClick`-handler doesn't get called if the click happened on a select checkbox.
This is technically a breaking change for anyone that actually wants the onRowClick to be triggered on selection as well. If that is indeed a use case, maybe we should add a configuration of some kind, either like an option, or by returning a boolean from `onRowsSelected` that determines if the select should call `onRowClick` as well.
Right now, our temporary fix for this is:
```js …
```

FIX onRowClick being triggered by row (de)selection

---

src/components/TableToolbarSelect.js

Current icon on hover: 
After this pr:
closes #364

Fix Toolbar icon size

---

src/components/TableBodyCell.js

Not sure if I should add event in the cellMeta or as a third argument...
(I would like to open a new tab when the user clicks the cell while pressing the ctrl key. That's why I need to access the MouseEvent)
Thank you

event available in onCellClick

---

package.json

Add a prepare script to package.json so contributors can run their fork directly from git, by adding the url of their fork in their main project's package.json using something like "mui-datatables": "https://github.com/benoitg/mui-datatables.git".  See https://docs.npmjs.com/cli/install for reference

Allow contributors to npm install directly from git remote url

---

src/components/TableToolbar.js

For issue https://github.com/gregnb/mui-datatables/issues/472
Removed the container prop for the filter and viewColumns buttons in the `TableToolbar.js` file. Without this, the container defaults to body and applies the `overflow: hidden` style to prevent the body from scrolling.
This matches the behavior of the rowsPerPage select menu.

Removed container prop on toolbar popovers to prevent body scroll

---

README.md
examples/custom-action-columns/index.js
src/MUIDataTable.js
test/MUIDataTable.test.js

Addresses https://github.com/gregnb/mui-datatables/issues/443.
There were two issues.
1. Missing fields in data were causing errors
1. Data arrays of arrays did not properly render `customBodyRender` when data was missing
Added an example under `custom-action-columns`. Not sure what the best name for this kind of use case would be, so I'm open to suggestions.
Let me know what you think.
UPDATED:
~~Added an API option for columns called `hasData` which defaults to `true`. When `false`, it signifies that a column should be skipped when checking for data. This is only relevant for the array of arrays data structure, but allows full use of empty columns or `customBodyRender` in those cases.~~
~~Not sure that the API option is super obvious, but I couldn't think of another way to distinguish …

Missing data for custom action columns

---

src/MUIDataTable.js

PR references #427 
- wire up className prop to component for users that are not using CSS in JS
---
In our case, we are using Material-UI with SCSS and `.scss` files for each component.  We'd like to be able to add classes to this component in order to override styles, rather than set up an MUI provider for the different instances of the component.

feature(MUIDataTable): pass className prop to underlying table

---

src/components/TableToolbar.js

Just a small tweak to allow the toolbar to utilise the whitespace to the right of the title.  It will still wrap once all the whitespace has been used without affecting the title.

Fixed the layout for the toolbar when adding custom buttons

---

README.md

corrected "row(s) selected" from "rows(s) selected"

---

src/MUIDataTable.js

Displays data in the same order as it comes from the API server.

Disable table sorting for server side data

---

src/MUIDataTable.js
test/MUIDataTable.test.js

Fixes two issues related to calculating the wrong order before passing it to sortTable function:
- When setting table data and finding a specific sort, don't toggle the existing sort order as this should be respected in this scenario.
- When toggling sort order, pass the new toggled order to sortTable instead of the original value.

 Fix sort ordering passed to sortTable function

---

README.md

TableBody.js passes `dataIndex` to setRowProps rather than `rowIndex`

setRowProps dataIndex

---

examples/resizable-columns/index.js
src/components/TableResize.js

Addresses https://github.com/gregnb/mui-datatables/issues/442.
- Adds demonstration code to the resize example
- Fixes bug in resize by preventing resize calculations when there is no actual resizing (hence, vanilla state updates will not recalculate width)
- Add some minor code quality improvements (orphaned vars, misspelled function)
There is still a slight stutter sometimes when state is changed before or after a column resizing event. An alternative fix which addresses everything including the stutter would be to remove the `componentDidUpdate` here: https://github.com/gregnb/mui-datatables/blob/master/src/MUIDataTable.js#L183. It's a much simpler fix, but I assumed that this might have unintended consequences, so I went for the slightly more complex fix.

Issue 442 - Column Resizing on Data Updates

---

src/MUIDataTable.js

Fix #519 (console warning and addition of a _undefined_ class if _paper_ is overridden).

Fix "paper" class override (#519)

---

src/components/TableBody.js

When the option **expandableRows** is set to true and **selectableRows** is set to false, the column span for the cell with the "noMatch" label is not correct. The correct value should be the *column count* plus 1 when setting to true either *expandableRows* or *selectableRows* options.

Fix the colspan value when 'expandableRows' is set and data is empty

---

README.md
docs/pages/index.js
src/MUIDataTable.js
src/components/TableBody.js
src/components/TableFilter.js
src/components/TableToolbar.js
test/MUIDataTableToolbar.test.js

Before this change, if user enters text in search bar and then clicks on filter icon (or any other icon on toolbar), the search text filed disappears. After this, the search bar does not disappear if it contains any search text.

Prevent closure of search bar  when any other toolbar buttons are clicked

---

examples/simple-no-toolbar/index.js
package-lock.json
package.json
src/MUIDataTable.js
test/MUIDataTable.test.js

Prevents the rendering of the toolbar when the all of the toolbar display items are missing, including:
- filter
- search
- print
- download
- viewColumns
- customToolbar
- title
Also adds a test case for this scenario, as well as an example on the example page.

Fix for Issue 258 (Do not render toolbar when all options are missing)

---

examples/customize-columns/index.js
src/utils.js
test/MUIDataTable.test.js

Fixes https://github.com/gregnb/mui-datatables/pull/570.
After the sort order was changed here https://github.com/gregnb/mui-datatables/pull/508/files, the ordering was swapped. We restore it by switching the values in the comparator.
Also updates the sort test and adds another one for the opposing sort direction.

Issue 565 Sort Order Swapped

---

README.md
src/MUIDataTable.js
src/components/TableBody.js
src/components/TableSelectCell.js
src/components/TableToolbarSelect.js
test/MUIDataTable.test.js
test/MUIDataTableBody.test.js
test/MUIDataTableHead.test.js

Fixes issue #274 extending the default behaviour of `selectableRows` so it supports one of `single`, `multiple` or `none`.
The checkbox in the header section will be only displayed when `selectableRows == 'multiple'`.
In the case of `single` selection, the checkboxes will be kept next to the rows, but no in the header. Also clicking any other row different than the selected one will change the selection.

Fix for issue 274

---

README.md
examples/customize-columns/index.js
test/MUIDataTable.test.js
test/MUIDataTableHead.test.js

Should help to close https://github.com/gregnb/mui-datatables/issues/213.
`customHeadRender` actually works properly as of `2.0.0-beta.59`, so the issue is out of date, however, I also noticed that the documentation around this feature was out of date, and could have been leading to confusion, so I did the following:
- Updated the documentation
- Added the option to example code
- Added testing around `customHeadRender` to help prevent future regressions

Issue 213 Clarify customHeadRender

---

src/MUIDataTable.js

This PR fix index for rowsSelected option. When rowsSelected are added in option, { index: rowPos, dataIndex: row } are added into selectedRowsData. However, the index could not be same as dataIndex, e.g, users filter data first and set rowsSelected. The PR fix #514

fix issue 514 index for rowsSelected option

---

src/components/TableSelectCell.js

Fixes https://github.com/gregnb/mui-datatables/issues/525.
The issue looked like a bug to me, but I thought it also might have been your intent to hide expandable icons and select boxes on responsive breakpoints, so I'm curious what you think. It does take up valuable space, but it also seems like it could be confusing UX to hide the options without any way to reinstate/toggle them back on (other than a wider viewport).
548px:

Allow select boxes and expandable row icons in responsive view

---

src/components/TableToolbarSelect.js

Fixes improper height for icon as demonstrated when hovering (notice the icon all the way on the right).
Broken:
Fixed:

Fix toolbar trash icon button height

---

src/components/TableToolbar.js

Some tooltips were inside the IconButton while others wrapped the IconButton. They now all wrap the IconButton.
This fixes #363 and fixes #211

Make tooltips consistent

---

src/MUIDataTable.js

seem you set table with old (`prevProps`) data instead of `this.props` (related to #585)
TL;DR;
@gabrielliwerant @gregnb I'm not sure I agree with this approach to use `componentDidUpdate` instead of `componentWillReceiveProps` but I got issue that state is not updating.
work fine now..

Suggestion to fix critical issue, table is not updated.

---

test/MUIDataTable.test.js

https://github.com/gregnb/mui-datatables/pull/585 introduced a regression, specifically when updating data via xhr requests. That issue was fixed here https://github.com/gregnb/mui-datatables/pull/597, but this PR adds a test that would have previously failed and now passes, helping to ward against this situation in the future.

Add test for serverSide=true with xhr

---

examples/component/index.js

Should help to close https://github.com/gregnb/mui-datatables/issues/219 by providing working examples of inputs in `component` example.

Add additional input examples for customBodyRender

---

README.md
examples/customize-rows/index.js
rollup.config.js
src/MUIDataTable.js
src/components/TableBody.js
src/components/TablePagination.js
test/MUIDataTable.test.js
test/MUIDataTableBody.test.js
test/MUIDataTableHead.test.js

I have a use-case in my project where I need a non-column based layout for smaller screens. This is to prevent horizontal scrolling, which is not a very good UX on mobile.
I still wanted to make use of the (great) filtering and sorting system of mui-datatables.
This PR adds a new `customRowRender` option to mui-datatables, that can be used like this:
```
customRowRender: ({ data }, rowIndex) => (
<div>
My Important data field: {data[0]}
</div>
)
```

customRowRender

---

README.md

I was looking to implement the feature requested in #43 , when I discovered the option already exists, it just is not documented.

Document option for hiding column from 'View Column' list

---

package-lock.json
src/components/TableFilter.js
src/components/TableFilterList.js
test/MUIDataTable.test.js

When there is only a single filter active in the columns config, use a single column for the filter grid list columns. This will allow the filter to take up 100% of the filter popover width.
Fixes: #604

Single grid column for single filter

---

src/components/TableFilter.js

In particular, the way margins were set, we had asymetry on the second column as well as a waste of space

Improve grid spacing in filters dialog

---

src/components/TableToolbar.js

Only handles the case where the search bar has entered text.
Helps https://github.com/gregnb/mui-datatables/issues/653.

Allow search bar to be shown when switching between toolbars

---

src/MUIDataTable.js

Attempt at a quick fix for https://github.com/gregnb/mui-datatables/issues/643.
There is at least one open PR that also incorporates something similar, but there's more going on, and I've been suspicious that this condition is needed for a while, so I want to try this as a hotfix and get community feedback incorporating other changes.

Allow derived column state to be rebuilt on prop change

---

src/components/TableBody.js

Closes https://github.com/gregnb/mui-datatables/issues/718.
We have a means to clean up the page out of bounds issue elsewhere, so this error is no longer needed and was causing breakage in certain circumstances.

Issue warning instead of throwing an error

---

src/components/TableFilter.js

Fix issue with width on custom filter component 

---

README.md
examples/customize-footer/CustomFooter.js
examples/customize-footer/index.js
src/components/TableFooter.js
src/components/TablePagination.js

Fix for https://github.com/gregnb/mui-datatables/issues/789
I've updated the customFooter callback to also take in the options parameter. With this parameter, one can more easily re-create the table pagination. I've also fleshed out the customize-footer example by showing how the Material UI TablePagination component can be used inside of the footer with other custom options.

Added options parameter to customFooter callback

---

README.md

I believe users would have an easier time using some customization like `downloadOptions` if the allowed properties were listed in the documentation. If I want to customize how the CSV file will be output using `downloadOptions` but I only know about the default properties `filename` and `separator`, I will have no idea about other possible customizations enabled with `filterOptions` (like `useDisplayedColumnsOnly` and `useDisplayedRowsOnly`).

List downloadOptions keys in docs for usability

---

docs/utils/withRoot.js
src/MUIDataTable.js
src/components/Popover.js

Will remove this lifecycle entirely in a later release
Closes https://github.com/gregnb/mui-datatables/issues/844

Silence deprecation warning by using the unsafe API

---

test/MUIDataTable.test.js
test/setup-mocha-env.js

I've made 2 small tweaks that allow the tests to work on both Material UI v3 and v4. In this PR I only change the tests and not the package.json or package-lock.json files (more on that below). Steps to test:
1. Do everything as usual, run the tests and see that they still work properly with v3.
2. Remove package-lock.json and ./node_modules
3. Update package.json: Change @materual-ui/core version to "4.3.0", react to "16.9.0" and react-dom to "16.9.0".
4. run "npm i".
5. run "npm run test" and see that the tests also work and pass with v4.
I didn't update package.json and package-lock.json since I figure it's in the cards to do that later down the road - though I'll note that I've been using the table with MUI v4 and I haven't seen any issues, though I know there are a few small things, …

Fix to make tests compatible with Material UI v3 and v4

---

src/components/TableToolbar.js
src/components/TableToolbarSelect.js

https://github.com/gregnb/mui-datatables/issues/676 - Made compatible with MUI v3 or v4.
https://github.com/gregnb/mui-datatables/issues/595 - Removed warning by following the suggestion of @mib00038.
Quick view of the changes available here: https://codesandbox.io/s/github/patorjk/mui-datatables/tree/676_595
I'm a huge fan of this library and am using it pretty extensively with v4. Hopefully I'm not being too annoying with all the PRs, I just have some extra time this week.

Fixes for 676 and 595

---

package-lock.json
package.json
src/MUIDataTable.js
test/MUIDataTable.test.js

Closes https://github.com/gregnb/mui-datatables/issues/878.
We want to override options when the component updates to enable changes in props to be reflected in the table. However, this overrides entire object properties when we really want to keep any defined nodes.
The fix is to merge/assign based on the property.
Additionally, there is some light refactoring here to make the deprecation notices and changes easier to manage.
Aside from the written test, I used the following code, added to the `selectable-rows` example and toggled the switch to test table/prop updates.
```
state = {
text: 'foo',
separator: ':'
rows: [10, 200, 500]
};
const options = {
textLabels: {
body: {
noMatch: this.state.text
}
},
downloadOptions: {
separator: this.state.separator
},
rowsPerPageOptions: …
```

Issue 878 Overwriting Props

---

README.md
examples/customize-search-render/CustomSearchRender.js
src/MUIDataTable.js
src/components/TableSearch.js
src/components/TableToolbar.js

https://github.com/gregnb/mui-datatables/issues/869
* Added documentation for onSearchClose and made a corresponding onTableChange event for it.
* Moved triggering of onSearchChange to MUIDatatable component so that it mirrors the "search" event. This also makes it so customSearch components don't have to manage this event.
* Made sure customSearch components can't double invoke this method if they're already setup to call it.
Quick view: https://codesandbox.io/s/github/patorjk/mui-datatables/tree/onSearchChange
Used this setup to follow event call order:
onSearchOpen: () => {
console.log('onSearchOpen');
},
onSearchClose: () => {
console.log('onSearchClose');
},
onSearchChange: (txt) => {
console.log('onSearchChange:'+txt);
},
onTableChange: (action, tableState) => { …

Fix for #869

---

src/utils.js

https://github.com/gregnb/mui-datatables/issues/873
Quick view: https://codesandbox.io/s/github/patorjk/mui-datatables/tree/sortFail
For test, change customizeFilter example to:
```
import { FormGroup, FormLabel, TextField } from '@material-ui/core';
import React from 'react';
import ReactDOM from 'react-dom';
import MUIDataTable from '../../src';
class Example extends React.Component {
render() {
const data = [
{
foo: 1,
bar: 2
},
{
foo: 3
}
];
const columns = [
{
name: "foo"
},
{
name: "bar"
}
];
var options = {
responsive: "scroll"
};
return (
<MUIDataTable title={'ACME Employee list - customizeFilter'} data={data} columns={columns} options={options} />
);
}
}
ReactDOM.render(<Example />, document.getElementById('app-root'));
```

Fix for #873

---

README.md
src/MUIDataTable.js
src/components/TableFilter.js
test/MUIDataTable.test.js

https://github.com/gregnb/mui-datatables/issues/880
* Updated how dropdown filters work so that only the "All" keyword is treated as a sign to remove the filters (thus allowing empty strings to be used as filter values).
Quick view: https://codesandbox.io/s/github/patorjk/mui-datatables/tree/empty-string-filter
The filterUpdate function only gets passed to 3 files: TableToolbar.js, TableFilter.js and TableFilterList.js. And only the latter 2 call it, and only TableFilter.js calls it with the type "dropdown" (TableFilterList.js removes filters by setting the type as "checkbox" or "custom", regardless of filterType).

Fix for 880

---

README.md
examples/examples.js
examples/serverside-filters/index.js
src/MUIDataTable.js
src/components/Popover.js
src/components/TableFilter.js
src/components/TableFilterList.js
src/components/TableToolbar.js
test/MUIDataTable.test.js
test/MUIDataTableFilter.test.js
test/MUIDataTableToolbar.test.js
webpack.config.js

Attempt to resolve https://github.com/gregnb/mui-datatables/issues/857 as well as any other requests around the difficulty of achieving server side filter functionality.
Handling filters on the server side is not an experience that has been optimized in this library. Some of the problems are:
- Lack of callbacks for the filter dialog, preventing different kinds of interactions with external APIs
- `filterList` in column options is connected to both the change in the fields in the filter dialog as well as the filter chip display, meaning that the display of applied filters cannot be stalled until a successful API call (they will be applied immediately regardless of any success/failure from an API call)
- Lack of ability to add custom buttons/functionality to the filter dialog
Here are the …

Issue-857 Server Side Filters

---

src/MUIDataTable.js

The `handleOptionDeprecation` function is being passed the original props instead of those with the default options merged in. This is causing false positive `console.error` output to be thrown.
Example:
Any table that doesn't include a `responsive` props option will see the `Invalid option value for responsive.` because the check isn't seeing the merged in default option.

Fix invalid option deprecation checks

---

src/components/TableToolbar.js

Closes https://github.com/gregnb/mui-datatables/issues/963.
Also closes https://github.com/gregnb/mui-datatables/issues/973.

Fix issue by properly checking for basic js objects and preserve displayed index

---

src/components/TableSelectCell.js

I want to improve accessbility of expandable rows in  https://github.com/gregnb/mui-datatables/issues/969

adding button wrapper for icon

---

test/MUIDataTable.test.js

This test sometimes times out when the test suite is run due to the way it is building new array data. It turns out that we don't need a new data set for this test, as we can use smaller rows per page number to get the same result on the existing data set in the test suite.

Upgrade testing performance and simplify

---

src/MUIDataTable.js
src/components/TableBody.js
src/components/TablePagination.js
src/utils.js
test/MUIDataTablePagination.test.js

Closes https://github.com/gregnb/mui-datatables/issues/942 and https://github.com/gregnb/mui-datatables/issues/994.

Fix issue where rows equal to row option would cause error

---

src/utils.js

Fixes #967 
Similar to #929 without refactoring.

Fix crash on downloading empty table as CSV

---

src/MUIDataTable.js

I notice that the `MUIDataTable` is mutating the props.columns.options value and it causes error when passing an immutable object to it. 
Example, I'm using `immer` to update state and it produces immutable data object (using deep-freeze under the hood).
I think it is better to not mutate the props values inside the component.
**Change**
- Replace code that mutate `props.columns.options` by spreading `column.options` into new options before mutating
**Example**
https://codesandbox.io/s/dazzling-dijkstra-kmuf2

Stop mutating column.options props and support immutable data object

---

src/components/TableHeadCell.js

With no sorting or a hint, the cursor still shows a pointer. I'm not saying this is the best solution, but I think the header shouldn't shouldn't show a pointer style of cursor when there is nothing to click on or additional behavior from hovering.

No Pointer style cursor for table head when no hint or sorting

---

test/MUIDataTable.test.js

A recent change #913 makes it's possible to identify a filterChange event by 'type === reset', which saved my day.
Here is a test case to ensure this feature exists forever.

add test case to verify reset type

---

src/MUIDataTable.js

Should prevent deprecation warnings from appearing frivolously based on default options, and should allows smoother transition in the next major version update.

Improve deprecation warnings and defaults for fixed header

---

examples/serverside-sorting/index.js

`npm run dev` fails on current master due to invalid casing in filename. This fixes that.

Fix require path in test

---

src/components/TableSearch.js

Move props from the `div` to the `input`
Fixing the Accessibility issue with the input not having an appropriate aria-label.

Fix for Issue #1152 Table Search Accessibility

---

examples/data-as-objects/index.js
examples/simple/index.js
src/MUIDataTable.js

This PR updates the table so that it maintains it's state between re-renders for properties that are not overwritten by the user (https://github.com/gregnb/mui-datatables/issues/807, https://github.com/gregnb/mui-datatables/issues/947, https://github.com/gregnb/mui-datatables/issues/1057). I've updated the "Simple" and "Data as Objects" examples with a "re-render" button that shows that search text, filters, selections, sorting, etc etc, are not lost when the table re-renders.
Some notes:
* Selected Rows and Expanded Rows reset if the data changes. This is why I've put the data on the component's state for the 2 examples I updated. In my own use, I found that if the table's data changed, it made no sense for the selections and expansions to stay in place.
* The Trash Can in the toolbar …

Updated table to make state persistent between renders

---

examples/Router/ExamplesGrid.js
examples/Router/index.js
examples/serverside-sorting/index.js

This PR adds a search box to the main example grid and adds a "return to index" button to each example. This makes navigating the examples easier. I also fixed a typo in one of the examples which was causing the repo not to work with codesandbox.
Quick view: https://codesandbox.io/s/github/patorjk/mui-datatables/tree/examplegrid_updates

Added search and "back to index" button to Example Grid

---

README.md
examples/examples.js
examples/large-data-set/index.js
src/index.js
src/plug-ins/DebounceSearchRender.js

This PR introduces the idea of "plug-ins" to the table. The tables lends itself to plug-ins in many areas and many of the use cases are common. The addition of plug-ins like this will **not** increase the file size for people who don't use them (since webpack will only add them to a person's bundle if they explicitly import them).
This plug-in is for the common use-case of a debounced search. It's useful in two areas:
* Server-side tables that don't want to execute an ajax request right away.
* Client-side tables which have a large data set.
I've included an example for how to use the plug-in in a new example called "Large Data Set". This example also shows the render time for the table and will be useful in another PR I submit later for performance improvements (this will need to be …

Debounced Search Plug-in

---

src/components/TableSearch.js

Keeps the listener off of the document for better UX.
Closes https://github.com/gregnb/mui-datatables/issues/1203.

Move keydown close event to element

---

src/components/TableToolbar.js

Fixes issue where closing via keydown causes the icon to become focused, which is confusing behavior

Prevent search icon focus on close

---

src/MUIDataTable.js
test/MUIDataTable.test.js

Ref: #1230 
I agree with this issue that the first time a column header is clicked for sorting, it should use ascending order. I suspect the current behaviour is a left-over of introducing the "none" `sortDirection` option recently.
Hopefully this PR will provide an acceptable solution, if maintainers agree with the change of behaviour.

Changed first time column sort order to be ascending

---

README.md
examples/custom-components/index.js
examples/examples.js
src/MUIDataTable.js
src/components/TableFilterList.js
src/components/TableFilterListItem.js
test/MUIDataTableCustomComponents.test.js

Currently there is no way to change built-in table components. This PR enables some customization.
This is a bit different that customizing with custom Material theme as this allows to react to given props.
In example: you can change the color of `Chip` in `TableFilterList` depending on current value. Useful for filtering by some status-like fields - you will have one `Chip` indicating status with visual feedback in filter list instead of duplicating this feedback throughout entire table.

Allow to pass custom table components

---

src/components/TableFilter.js

This forwards `filterData` to custom filters `display` callback.
Reason: Users who want to do custom rendering but are happy with the options already calculated by mui-datatables.

Propagate filterData to custom filters

---

src/components/TableBody.js

Change Typography from `h6` to `p`.
Put text inside `strong` to keep emphasis and bold text.
http://web-accessibility.carnegiemuseums.org/foundations/semantic/

Prevent skipping of heading level for Accessibility and standard semantic HTML purposes

---

webpack.config.js

Build has too many logs. 😭 
So reduce the log... change stats options(errors-warings)
ref : https://webpack.js.org/configuration/stats/
devserver host set localhost #1042 
+ remove unused import (path)
What do you think?
thanks~

fix webpack config

---

README.md
examples/customize-columns/index.js
examples/serverside-pagination/index.js
src/MUIDataTable.js
src/components/TableHead.js
src/components/TableHeadCell.js
test/MUIDataTable.test.js

In the current API, the table's sort direction is held in one of the column options objects. This has the following problems:
* It leads to ambiguity if multiple columns have this field set.
* It's makes it hard to implement multiple level sorting (where a table is first sorted by 1 column, and then for values that are the same a second column is used to sort). You can see an example of this in [jQuery Datatables](https://datatables.net/) - click a column header, and then shift+click another header. The second column is used to break ties.
* It adds unnecessary complexity to users who use the serverSide option, since a sort value is typically passed to the server separately, and in the current implementation it burred in one of the column's options.
This PR removes sortDirection from the …

Added sortOrder option (deprecating sortDirection on columns object)

---

README.md
examples/customize-footer/index.js
src/MUIDataTable.js
test/MUIDataTable.test.js

This PR aims to solve the main problem brought up in https://github.com/gregnb/mui-datatables/pull/1266, which is that it is not currently possible for a column to have it's own footer cell. This stems from the footer of the table being wrapped in its [own table](https://github.com/gregnb/mui-datatables/blob/master/src/components/TableFooter.js#L17). There are good reasons for this (ex: the resizable columns feature), and while refactoring the footer to not be inside its own table element might be possible, it would be messy and potentially lead to bugs.
In order to allow columns to have their own footer, this solution instead proposes a new option called customTableBodyFooterRender  which allows the user to render a footer under the table body and above the table's pagination footer. The …

Added customTableBodyFooterRender

---

README.md
examples/customize-filter/index.js
examples/large-data-set/index.js
examples/serverside-filters/index.js
examples/simple/index.js
package-lock.json
src/MUIDataTable.js
src/components/Popover.js
src/components/TableFilter.js
src/components/TableFilterList.js
src/components/TableToolbar.js
test/MUIDataTable.test.js
test/MUIDataTableFilter.test.js

This will most likely be my last feature PR before v3 is released. This PR is an update to https://github.com/gregnb/mui-datatables/pull/1093
The table currently has a serverSideFilterList option to help with filtering for serverSide tables. The idea is to delay adding filter chips until a user "applies" the filters. This feature has the following problems:
* It requires the user manage an external filterList.
* Having a serverSideFilterList and a client-side filterList is not DRY.
* It does not help with filtering for tables with large data sets.
This PR offers up an alternative solution that doesn't have the above problems. It does the following:
* It adds an option called "confirmFilters". When true, filters won't be applied to the table unless they are "confirmed".
* Confirming …

Added confirmFilters option (deprecates serverSideFilterList)

---

src/components/TableHead.js

This is an edge case that occurs for the selectToolbarPlacement option. It's accounted for when using the disableToolbarSelect option. To re-create:
* Set selectToolbarPlacement to "none" or "above".
* Select all rows.
* Do a search so that only a few rows will show up.
* The header checkbox won't be checked.
This PR will make it so the checkbox stays checked. Workaround is to use disableToolbarSelect option.

Minor bug fix for header checkbox when selectToolbarPlacement = 'none' or 'above'

---

examples/resizable-columns/index.js
src/MUIDataTable.js
src/components/TableResize.js
test/TableResize.test.js
test/setup-mocha-env.js

The resizableColumns feature currently doesn't work when there is left margin on the container for the table (see https://github.com/gregnb/mui-datatables/issues/1280).
This PR makes some adjustments so that the resizableColumns work with leftMargin. The PR can be viewed below: (see the "Resizable Columns" example)
https://codesandbox.io/s/github/gregnb/mui-datatables/tree/resizeLeftMargin

Bug fix for #1280 / Fix issues with resizableColumns

---

examples/draggable-columns/index.js
examples/examples.js
examples/infinite-scrolling/index.js
examples/resizable-columns/index.js
package-lock.json
package.json
src/MUIDataTable.js
src/components/TableHeadCell.js
src/components/TableToolbar.js
src/components/TableViewCol.js
src/hooks/useColumnDrop.js
test/MUIDataTableViewCol.test.js
webpack.config.js

This release would fix the following:
* Allow draggable columns to work with excluded columns (https://github.com/gregnb/mui-datatables/issues/1364).
* Make it so cursor isn't a hand if the column isn't draggable.

version 3.1.2 (fixes)

---

README.md

Custom components were introduced per the following PR/commit but lack the add to the Table of Contents:
- https://github.com/gregnb/mui-datatables/pull/1167
- https://github.com/gregnb/mui-datatables/pull/1300/commits/12c08a575dc327f7766b2982267d170d756893e0

Missing link to Custom Components in README's ToC

---

package.json
src/hooks/useColumnDrop.js

Fix for https://github.com/gregnb/mui-datatables/issues/1393
I would like some automated tests for drag and drop columns, but after spending over 2 hours on it, I've decided to throw in the towel. The docs on react-dnd are not great and info on testing is even worse, I can't seem to make any headway. Additional reference: https://github.com/react-dnd/react-dnd/issues/1506

Fix 1393 / Draggable column with no select column don't work correctly if there's a left margin

---

src/components/TableFooter.js
test/MUIDataTableFooter.test.js
test/MUIDataTablePagination.test.js

Refactor from class component to functional component
ref : #1346
Sorry. When I split it in PR, it's lot..
codeSandBox : http://codesandbox.io/s/github/wdh2100/mui-datatables/tree/functional/tableFooter

Refactoring TableFooter

---

src/components/TableSearch.js
src/components/TableViewCol.js

Refactor from class component to functional component
ref : #1346
Sorry. When I split it in PR, it's lot..
codeSandBox : http://codesandbox.io/s/github/wdh2100/mui-datatables/tree/functional/tableSearchAndViewCol

Refactoring TableSearch and TableViewCol

---

README.md
examples/customize-filter/index.js
src/MUIDataTable.js
src/components/TableBody.js
src/components/TableFilterList.js
src/components/TableFilterListItem.js
test/MUIDataTableFilterList.test.js
test/MUIDataTableHead.test.js

New option that allows you to add props to the Filter Chip component. Works identically to the other setXProps methods. Example:
setFilterChipProps: (colIndex, colName, data) => {
//console.log(colIndex, colName, data);
return {
color: 'primary',
variant: 'outlined',
className: 'testClass123',
};
}
Useful for easily customizing to a filter chip. This can already be done through the custom component feature, but doing it that way is a bit of work. Using setFilterChipProps would make customization a lot easier.

Added setFilterChipProps

---

src/MUIDataTable.js
test/MUIDataTable.test.js

The table currently uses the method unsafe_componentWillMount in the main component. React is removing this lifecycle method in version 17 and it currently gives a warning message to developers using strict mode (https://github.com/gregnb/mui-datatables/issues/1261). The method is deemed unsafe because it can lead to memory leaks if not used properly.
React recommends using the constructor is initialize state or componentDidMount for initialization that requires DOM nodes. Only the former is relevant to mui-datatables, so the code has been refactored to use the constructor.

Refactored out unsafe_componentWillMount

---

docs/utils/CodeSnippet.js
package-lock.json
package.json
src/MUIDataTable.js
src/components/JumpToPage.js
src/components/TableBody.js
src/components/TableBodyCell.js
src/components/TableBodyRow.js
src/components/TableFilter.js
src/components/TableFilterListItem.js
src/components/TableHead.js
src/components/TableHeadCell.js
src/components/TableHeadRow.js
src/components/TableSelectCell.js

See: 
- https://material-ui.com/getting-started/faq/#whats-the-clsx-dependency-for
- https://github.com/mui-org/material-ui/pull/14152

Replace classnames with clsx

---

README.md
examples/column-sort/index.js
examples/examples.js
src/MUIDataTable.js
test/MUIDataTable.test.js

This PR is a continuation of https://github.com/gregnb/mui-datatables/pull/951. I've simply updated the code for the latest branch, expanded upon the example, and made it so sortCompare takes precedence over customSort.
This feature has been requested/come up several times recently (https://github.com/gregnb/mui-datatables/issues/1011#issuecomment-645651798, https://github.com/gregnb/mui-datatables/issues/1336#issuecomment-648682275, https://github.com/gregnb/mui-datatables/issues/1394). 
sortCompare Interface
---------
```typescript
(order: 'asc'|'desc') => ({data: val1}, {data: val2}) => number
```
example:
```javascript
columns = [
{
name: "Name",
options: {
sort: true,
sortCompare: order => ({data: val1}, {data: val2}) => (val1.length - val2.length) * (order === 'asc' ? 1 : -1)
}
}
] …
```

Added support for custom sort function for columns

---

README.md
examples/column-sort/index.js
examples/customize-columns/index.js
examples/customize-sorting/index.js
examples/examples.js
examples/resizable-columns/index.js
examples/simple/index.js
package.json
src/MUIDataTable.js
src/components/Popover.js
src/components/TableFilter.js
src/components/TableResize.js
src/hooks/useColumnDrop.js
src/utils.js
test/MUIDataTable.test.js
test/MUIDataTableFilter.test.js
test/MUIDataTableToolbar.test.js
test/MUIDataTableToolbarSelect.test.js
test/TableResize.test.js
test/UseColumnDrop.test.js
test/setup-mocha-env.js
test/utils.test.js

Branch for the 3.3.0 release of mui-datatables. It contains the following:
* Added support for custom sort function for columns (columns[colIndex].options.sortCompare). Thanks to @GuyShaanan (https://github.com/gregnb/mui-datatables/pull/1424) 
* Test coverage updates to get coverage above 80% (https://github.com/gregnb/mui-datatables/pull/1425)
* Third click to reset table sorting (available by setting options.sortThirdClickReset to true). Thanks to @danielbyun (https://github.com/gregnb/mui-datatables/pull/1430)
* Added sortDescFirst option to allow table to sort in desc order first (https://github.com/gregnb/mui-datatables/issues/1411)
* Fix for resizable tables when selectableRows="none" (https://github.com/gregnb/mui-datatables/issues/1433)
* Updated searchText README …

mui-datatables v3.3.0

---

package-lock.json
package.json
src/components/TableResize.js
src/hooks/useColumnDrop.js

This PR contains the following fixes:
* Fix for making draggable columns work properly when there is a scroll offset on the table (ex: a table with 20 columns where one scrolls to the right to see columns).
* Fix for resizable columns when certain columns are hidden. Also implements a better fix for selectableRows="none" (which was put into 3.3.0).

Bug fix for resizable columns and draggable columns

---

README.md
examples/custom-components/index.js
examples/expandable-rows/index.js
package.json
src/MUIDataTable.js
src/components/ExpandButton.js
src/components/TableBody.js
src/components/TableFilter.js
src/components/TableSelectCell.js
src/components/TableViewCol.js
src/index.js
test/MUIDataTable.test.js

* rowsPerPage now allows updates on re-renders. (https://github.com/gregnb/mui-datatables/issues/1445)
* page option now updates the table on re-renders. (https://github.com/gregnb/mui-datatables/issues/1460)
* Added "data-description" prop to Checkbox component. This props describes where a checkbox is (valid values: ['row-select', 'row-select-header', 'table-filter', 'table-view-col']). This can be useful for cases where you want different types of selection (ex: replacing the row selection checkboxes with radio buttons). (https://github.com/gregnb/mui-datatables/issues/1461, https://github.com/gregnb/mui-datatables/issues/1453)
* Made the expand row button replaceable via the components option (ExpandButton). (https://github.com/gregnb/mui-datatables/issues/1446)
* IE11 updates which …

IE11 and rowsPerPage update

---

src/MUIDataTable.js
src/components/TableToolbar.js

This pull request makes the `TableFilter` component swappable from client code. This is very useful in cases when special customizations needs to be done in the filter dialog. The alternative to this is overriding the `TableToolbar` component and swap `TableFilter` from there, which is not desirable at all.

feat($general): make TableFilter swappable

---

README.md
examples/custom-components/index.js
examples/expandable-rows/index.js
package-lock.json
package.json
src/MUIDataTable.js
src/components/ExpandButton.js
src/components/TableBody.js
src/components/TableFilter.js
src/components/TableSelectCell.js
src/components/TableToolbar.js
src/components/TableViewCol.js
src/index.js
test/MUIDataTable.test.js

Branch for the 3.4.0 release of mui-datatables. It contains the following:
* rowsPerPage now allows updates on re-renders. (https://github.com/gregnb/mui-datatables/issues/1445)
* page option now updates the table on re-renders. (https://github.com/gregnb/mui-datatables/issues/1460)
* Added "data-description" prop to Checkbox component. This props describes where a checkbox is (valid values: ['row-select', 'row-select-header', 'table-filter', 'table-view-col']). This can be useful for cases where you want different types of selection (ex: replacing the row selection checkboxes with radio buttons). (https://github.com/gregnb/mui-datatables/issues/1461, https://github.com/gregnb/mui-datatables/issues/1453)
* Made the expand row button replaceable via the components option (ExpandButton). …

mui-datatables v3.4.0

---

src/MUIDataTable.js

This PR adds the option to pass a `tableId` prop to the `<MUIDataTable />` component.
Additionally it sets a default `tableId` when `options.draggableColumns.enable` is set to `true` and the `tableId` prop hasn't been provided by the user.
It fixes #1452.
@patorjk i'm not used to enzyme as a testing library and I struggled finding a way to properly test for the availability of the `data-tableid` attribute. Hence I haven't added test cases for now. Could you guide me a bit in this?

feat: add option to pass tableId as a prop

---

src/MUIDataTable.js

Issue Ticket: #1479 
The library is already pulling in `lodash.isequal`, so I decided to leverage that function for a deep-object comparison in the `Array.findIndex()` function predicate.
Personally, I think it would be better to either: pass in a custom comparator as a prop, or return the filter `value` instead of `filterPos` to allow the user to define their own logic in `update()`. However, the deep-object comparison method does not break any existing contracts/functionality or require adding an additional prop.

Bugfix/1479: Return Correct filterPos using Deep-Object Equality

---

src/MUIDataTable.js

> display:'excluded' must be excluded from the search, as the user cannot see it in any way.
Fix #1474

Fix search results for excluded options

---

README.md
examples/array-value-columns/index.js
src/MUIDataTable.js

This adds a "filterArrayFullMatch" option to the table that defaults to true, to decide how to handle array filtering.
Default remains the same : if you have several filter values selected, for a row to show, the column value needs to include every filter values.
If filterArrayFullMatch is false though, then we check if at least one of the filter values is in the column value.
I made some changes to the array-value-columns example to include both use cases, I changed the example component to be a function which is why the commit is a bit long.
I thought this use case I added should be pretty common, and would be interesting to add support for.
Also this is my first PR, so let me know if you're interested with this option, and if so tell me if anything is wrong.

Add support for 'any match' filter for array values

---

src/MUIDataTable.js
src/components/TableHeadCell.js

This pull request actually has two desired outcomes
1) I'm using react-dnd in other components with a different backend for IE performance reasons - i'd like to use my custom backend everywhere
2) I was having issues initially and wanted to just disable loading the drag-and-drop component from even loading - this now enabled that by passing  components={{DragDropBackend: null}}

Allow custom react-dnd backend

---

examples/text-localization/index.js
package-lock.json
src/components/TablePagination.js

Hello, guys. This is my first Github contribution. I noticed that the textLabel for 'next' and 'previous' were not being applied in the titles for the 'nex't and 'previous' buttons in the pagination area. Only the aria-label were being applied. So, I made this correction to add both titles. Please, let me know if you need anymore information on this PR.

Adding title props in both backIconButtonProps and nextIconButtonProps

---

.babelrc
.eslintrc
examples/Router/index.js
examples/serverside-pagination/index.js
package-lock.json
package.json
webpack.config.js

- add @babel/runtime-corejs3
- add core-js
This PR added the process of inserting core-js during build and transpiling.
I want to show it as CodeSansBox, but CodeSandBox is not support IE
So you have to check it locally.
I've tested it in Chrome and IE.
Solved to fix this https://github.com/gregnb/mui-datatables/pull/835
I think... It seems to be insufficient, but there is no problem with the build and transpiling.
thanks!
ref : 
- https://babeljs.io/blog/2019/03/19/7.4.0
- https://alexbogovich.com/blog/core-js/

Implement bundle with babel core-js@3

---

src/components/TableToolbar.js

Fix #1563
Do not call the function at the time of event call.

BugFix onFilterDialogClose event

---

examples/simple/index.js
src/components/TableFilter.js

#1559
The usability is the same.
However, there may be some differences.
It looks like the use of abnormal components(`GridList`), so I fixed it.
And there are also component changes in v5.
GridList => ImageList
These changes seem to clarify the purpose.
https://material-ui.com/components/grid/
https://material-ui.com/components/grid-list/

Replace gridList to grid

---

package.json
src/components/ExpandButton.js

Per Material UI's guide on minimizing bundle size, It appears a recent mui-datatables update [#1591](https://github.com/gregnb/mui-datatables/issues/1591) broke tree-shaking by importing material icons incorrectly.  This PR attempts to remedy that so projects importing mui-datatables aren't bloated by importing the full icon set.
Example:
```javascript
// uses tree-shaking, only imports the Remove icon
import RemoveIcon from '@material-ui/icons/Remove';
// imports all of @material-ui/icons (requires a Babel plugin to only include the Remove icon)
import { Remove } from '@material-ui/icons';
```
I came upon this issue when trying to reduce the bundle size of one of my projects and found that the full icon set was still being included even though I followed the Material UI guide.  I …

Fixed @material-ui/icons imports to allow tree-shaking

---

src/components/TableHeadCell.js

Fixes #1629
- Use Material UI Button for sort (adds focus, hover styles)
- Fix help and arrow alignment
- Center tooltip on button
- Fix duplicate `tabindex`

Fix sort header: duplicate tabindex, focus/hover style issues

---

package-lock.json
src/MUIDataTable.js
src/components/TableBody.js
src/components/TableHead.js
test/MUIDataTable.test.js
test/MUIDataTableBody.test.js
test/MUIDataTableToolbarCustomIcons.test.js

- auto generated the unique table id if not passed regardless of other options
- added tableId to row and cell id prop to ensure ids are unique if there are multiple tables in a page

ensure ids are unique when rendering multiple tables

---

src/components/ExpandButton.js
src/components/JumpToPage.js
src/components/TableFilter.js
src/components/TableHead.js
src/components/TableSelectCell.js

I performed a text search for anything importing `from '@material-ui/core` and replaced the results with second level imports, so that the entire @material-ui/core directory is not pulled into bundles.

Removing top level imports to reduce bundle sizes.

---

src/components/TableToolbar.js

my company's QA team couldnt select the download csv button using the cypress automation testing tool because there was a space in the localization config of downloadCsv.
this fix makes it so that you can use whatever localization text you want and remove the whitespaces only in the data-testid attributes.

cut out space in data-testid for automation tools

---

src/components/TableResize.js

Fixing #1716 by adding one separator less than the number of visible columns

Adding one separator less than the number of visible columns

---

README.md
src/MUIDataTable.js
src/components/TableHead.js
src/components/TableSearch.js
src/components/TableToolbar.js
test/MUIDataTableToolbar.test.js

Related to #1125 and #1686
This adds the option to have the search bar always open. This sets the search bar to be open and removes the close option. It also removes the search icon from the toolbar, since that would allow the search bar to be closed. An alternative would be to keep the icon but disable its on click, would be happy to make that change if that's preferred.

Search always open

---

README.md

Updated the global theme sample present in the readme https://github.com/gregnb/mui-datatables/issues/1842

readme: Update the readme

---

src/plug-ins/DebounceSearchRender.js

This PR fixes the #1830 issue.

Fixed the issue with the searchAlwaysOpen when using debounce

---

README.md
package-lock.json
package.json

Hi,  
**UPTATE**: Mainly, this PR fixes #1878 and #1842. Beside;
A new version of `tss-react` has been released, `tss-react` no longer requires it to be a peer dependency.  
I have updated the `package.json` and the `README.md` to take advantage of this.  
I also made a few more changes in the  dependency requirement:
-  `@emotion/react`: It's a peer dependency of `@mui/material` and you use it directly. This means that `@emotion/react` should be a peer dependency of `mui-datatalbes`. `@emotion/react` is a module that uses `React.Context` thus there can't be multiple copies of the lib in a project: It can't be in `dependencies`. 
- `@emotion/styled`: It's a peer dependency of `@mui/material` but you never use it directly => It should be in `devDependencies` not `dependencies`.  
This PR …

Fix customization with createTheme

---

README.md

https://github.com/gregnb/mui-datatables/pull/1882#issuecomment-1140927103

Fix mui import statements

---

src/components/TableBodyCell.js

`isEmpty` being in `otherProps` means it was getting passed to `TableCell` which eventually causes a (harmless) warning to be thrown regarding that prop. This removes isEmpty from otherProps and just destructures it like other props.

Fixed an issue where empty cells would throw an error

---

src/MUIDataTable.js

If the table is placed near tooltips or other elements with z-indexes, some parts of the table (notably the header) can overlap in unexpected ways. Placing the component in an isolated stacking context with `isolation: isolate` makes sure that the z-indexes inside the component only interact with other indexes inside the component, causing the component as a whole to be treated as a single object, which is more coherent and desirable in practically all situations.

place component in isolated stacking context

---

src/MUIDataTable.js

This is my attempt at fixing https://github.com/gregnb/mui-datatables/issues/1913. I'm not sure `@global` is actually supported by `tss-react`, so I rewrote this part without using it. Not sure if that's the best way to do it, any suggestions are welcome 🙂 
I also unfortunately wasn't able to run tests locally, when running tests locally with `npm test` I get this error:
```
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at Object.help (/Users/anya/mui-datatables/node_modules/yargs/lib/usage.js:240:22)
at Object.self.showHelp (/Users/anya/mui-datatables/node_modules/yargs/lib/usage.js:432:15)
at Array.<anonymous> (/Users/anya/mui-datatables/node_modules/mocha/lib/cli/cli.js:53:13)
at Object.fail …
```

fix: hide column in print mode when `print: false`

---

src/MUIDataTable.js

Is there a way to show TableToolbarSelect always?
I redefined the TableToolbarSelect component, now I have my own logic for this component, but I also need it to always be on the screen, and it appears only when selecting an object from the table.
I saw the selectToolbarPlacement property that is responsible for showing TableToolbarSelect. Added the always property there. Please do so that I can customize my TableToolbarSelect and be able to show it always.

ToolbarSelect should always shown
